### PR TITLE
Finished tasks

### PR DESCRIPTION
**Pull request by Kehnnie**

### CODE REVIEW

**Review by TelRich — COMMENTED** [review]
Nice work @Kehnnie 

I'd love for you to modify your visual.

**Comment by TelRich** [comment]
image

Can you make your chart look like this. It will require you to do more research.

**Comment by Kehnnie** [comment]
I have updated the visual. I am still researching on how i can make the data labels visible

**Comment by Kehnnie** [comment]
I have made the data labels visible. Done with it.

**Comment by Kehnnie** [comment]
I have made the changes

**Comment by Kehnnie** [comment]
Updated the other visuals

**Pull request merged**
